Jla 12
DamianWDev/JLearning pull request #6
Opened 2022-05-20 22:46 UTC by Dawid55a

2022-05-22 17:06 UTC, DamianWDev requested changes

2022-05-22 17:06 UTC, DamianWDev commented on API/module/manga/manga_repository.py
> +            await session.commit()
[find_all] has defined session type but [insert] doesn't?

2022-05-22 17:06 UTC, DamianWDev commented on API/module/manga/manga_route.py
> +@router.get('/mangas/', status_code=status.HTTP_201_CREATED, response_class=ORJSONResponse)
created status in get EP?

2022-05-22 21:10 UTC, DamianWDev requested changes
names, useless whitespaces lines in imports, names, can't run app, NAMES!

2022-05-22 21:10 UTC, DamianWDev commented on API/module/db/model/manga.py
> +        img_path={self.img_path})
missing img_extension

2022-05-22 21:10 UTC, DamianWDev commented on API/module/manga/manga_repository.py
> +        manga = Manga(name=name, img_path=img_path, extension=extension)
rename img_extension

2022-05-22 21:10 UTC, DamianWDev commented on API/module/manga/manga_service.py
> +        await self.manga_repository.insert(name, filename, extension)
rename img_extension

2022-05-27 22:27 UTC, Dawid55a commented on API/module/db/database.py
> +            await conn.run_sync(Base.metadata.create_all)
Will be removed when miggration will be added

2022-08-15 13:57 UTC, merged